### ISSUE TITLE
Project Requirements and English Resources

### ISSUE THREAD

**Issue by happyTonakai** [mrpep/Fast-Music-Source-Separation#1]
Dear Mr. Leonardo Pepino,

I'm interested in your thesis project. However, I have a couple of questions regarding the code and methodology used in your thesis.

Requirements: Could you please specify the project's technical requirements, such as the required Python version, Keras version, and TensorFlow version? Knowing this information will help me set up the project correctly.

Methodology Details: I've already walked through your blog post [here](https://mrpep.github.io/Fast-Music-Source-Separation/), where you introduce the CNN architecture. However, I'm interested in a more detailed understanding of the methodology you used. Is there any additional documentation or a paper in English that provides a more comprehensive explanation of your approach? The thesis appears to be written in a non-English language.

Thank you.

ZR Han.

**Comment by happyTonakai** [comment]
I found the keras version is 2.1.5 from the pdf5 file, and the corresponding compatible tensorflow version is 1.8. However I came across this error:
```
Traceback (most recent call last):
  File "separate.py", line 29, in <module>
    model.load_weights("pesos.hdf5")
  File "C:\Users\HanZR\miniconda3\envs\tf1\lib\site-packages\keras\engine\topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Users\HanZR\miniconda3\envs\tf1\lib\site-packages\keras\engine\topology.py", line 3328, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```

-----
Edit:
Never mind, I removed `.decode('utf8')` in the `\keras\engine\topology.py` and it works fine.
